version: '3.8'
services:
  mm-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mm_pgdata:/var/lib/postgresql/data

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    depends_on:
      - mm-postgres
    env_file:
      - .env
    ports:
      - "8065:8065"
    volumes:
      - mm_data:/mattermost/data
      - mm_logs:/mattermost/logs
      - mm_config:/mattermost/config
      - mm_plugins:/mattermost/plugins
      - mm_client_plugins:/mattermost/client/plugins

volumes:
  mm_pgdata:
  mm_data:
  mm_logs:
  mm_config:
  mm_plugins:
  mm_client_plugins:
