services:
  mm-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    depends_on:
      - mm-postgres
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8065:8065"
    volumes:
      - ./volumes/data:/mattermost/data
      - ./volumes/logs:/mattermost/logs
      - ./volumes/config:/mattermost/config
      - ./volumes/plugins:/mattermost/plugins
      - ./volumes/client_plugins:/mattermost/client/plugins
